### ISSUE TITLE
timetable problem

### ISSUE THREAD

**Issue by BenedictTom** [vtfanta/ILP-Timetable-Maker#1]

**Comment by vtfanta** [comment]
@chwyxy 
Hello,
thank you for taking interest in my project!
The showcased timetable is applicable to a 9 grade primary school in Czechia. During the first four years of study, the small pupils are taught only by their so-called "class teacher" (except for the foreign language lessons). The labels for these teachers, T1-T4 are therefore excluded from the requirements put upon the other teachers.

I hope this answers your question. I can provide further comments if needed.
